export const POKEMON_TYPES = [
  { name: "Bug", color: "lime" },
  { name: "Dark", color: "gray" },
  { name: "Dragon", color: "purple" },
  { name: "Electric", color: "yellow" },
  { name: "Fairy", color: "magenta" },
  { name: "Fighting", color: "orange" },
  { name: "Fire", color: "red" },
  { name: "Flying", color: "geekblue" },
  { name: "Ghost", color: "purple" },
  { name: "Grass", color: "green" },
  { name: "Ground", color: "gold" },
  { name: "Ice", color: "cyan" },
  { name: "Normal", color: "gray" },
  { name: "Poison", color: "purple" },
  { name: "Psychic", color: "magenta" },
  { name: "Rock", color: "yellow" },
  { name: "Steel", color: "gray" },
  { name: "Water", color: "blue" }
]